### ISSUE TITLE
Propojit dohromady vše

### ISSUE THREAD

**Issue by milan-sedivy** [madebyqwerty/shift#1]
```[tasklist]
### Tasks
- [x] Hodit to do jedné složky
- [ ] Nastavit Docker compose soubor pro všechny service
- [x] Vytvořit readme k spuštění na localhostu
```
