### ISSUE TITLE
Kompletace skenu

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/shift#100]
```[tasklist]
### Tasks
- [ ] Vytvořit ui na zobrazení skenu
- [ ] Vytvořit ui na editaci toho skenu
- [ ] Poslat opravený sken na kompletaci
```
