### ISSUE TITLE
Zprovoznit rabbitmq

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/shift#26]
```[tasklist]
### Tasks
- [ ] https://github.com/madebyqwerty/shift/issues/27
- [ ] https://github.com/madebyqwerty/shift/issues/28
- [ ] https://github.com/madebyqwerty/shift/issues/30
- [ ] https://github.com/madebyqwerty/shift/issues/39
- [ ] https://github.com/madebyqwerty/shift/issues/58
```
