### ISSUE TITLE
Předělat frontend na desktop

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/shift#33]
```[tasklist]
### Tasks
- [ ] Předělat posílání
- [ ] Vytvořit komponent který zobrazuje nahrávající a zpracovávájící se soubory
- [ ] Vytvořit komponent na editaci vrácených dat z OCR
- [ ] Vytvořit funkci na nahrání více záznamů
```
