### ISSUE TITLE
User story: skenování

### ISSUE THREAD

**Issue by tomaskebrle** [madebyqwerty/shift#62]
Já jako uživatel bych chtěl aby, mohl naskenovat papír na mobilu, ale absence upravit na notebooku, protože mám tlustý prsty a na telefonu se mi to blbě dělá 😄 
```[tasklist]
### Tasks
- [ ] https://github.com/madebyqwerty/shift/issues/26
- [ ] https://github.com/madebyqwerty/shift/issues/63
- [ ] https://github.com/madebyqwerty/shift/issues/67
- [ ] https://github.com/madebyqwerty/shift/issues/69
- [ ] https://github.com/madebyqwerty/shift/issues/65
- [ ] https://github.com/madebyqwerty/shift/issues/56
- [ ] https://github.com/madebyqwerty/shift/issues/64
- [ ] https://github.com/madebyqwerty/shift/issues/66
- [ ] https://github.com/madebyqwerty/shift/issues/68
```
